name: Sync to Hugging Face hub
on:
  push:
    branches: [master]
  

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Set up GIT LFS
        run: git lfs install

      - name: Pull LFS objects
        run: git lfs pull
        
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # git config --global user.email "josephrodrigo42@gmail.com"
          git config --global user.email "w1956366@my.westminster.ac.uk"
          git config --global user.name "itsjorigo"
          git lfs push origin master
          git push https://itsjorigo:$HF_TOKEN@huggingface.co/spaces/itsjorigo/movie-recommendation-search master
